name: wandermate
description: AI-powered location based travel and place discovery mobile application developed with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Flutter UI
  cupertino_icons: ^1.0.6
  sizer: ^3.0.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0

  # State Management
  flutter_riverpod: ^2.5.1
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.0

  # Networking
  http: ^1.1.0
  connectivity_plus: ^6.1.4

  # Navigation
  go_router: ^14.6.1

  # Maps & Location
  google_maps_flutter: ^2.10.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # AI
  google_generative_ai: ^0.4.7

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.2
  share_plus: ^7.2.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/map_style.json